In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
K = np.array([[-0,-1, 0],[-1, 4, -1], [0,-1,0]])
print (K)
print (K.shape)

[[ 0 -1  0]
 [-1  4 -1]
 [ 0 -1  0]]
(3, 3)
